//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanDT.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien_ChucNang
    {
        public int IDnhanVien { get; set; }
        public int IDnchucNang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual CHUCNANG CHUCNANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
