//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanDT.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Category()
        {
            this.tb_postBaiViet = new HashSet<tb_postBaiViet>();
            this.tb_ThongBaoMoi = new HashSet<tb_ThongBaoMoi>();
        }
    
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public string SeoTieuDe { get; set; }
        public string MieuTa { get; set; }
        public string SeoMoTa { get; set; }
        public string SeoTuKhoa { get; set; }
        public Nullable<System.DateTime> CreatyDate { get; set; }
        public string biDanh { get; set; }
        public Nullable<int> idNhanVien { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_postBaiViet> tb_postBaiViet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ThongBaoMoi> tb_ThongBaoMoi { get; set; }
    }
}
