//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanDT.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_datNhanThongBao
    {
        public int ID { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
