//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanDT.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProductImage
    {
        public int IDImage { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string image { get; set; }
        public string idDefault { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Craetedby { get; set; }
    
        public virtual TB_PRODUCT TB_PRODUCT { get; set; }
    }
}
