//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanDT.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PRODUCT()
        {
            this.tb_orderDeTail = new HashSet<tb_orderDeTail>();
            this.tb_ProductImage = new HashSet<tb_ProductImage>();
        }
    
        public int ID { get; set; }
        public string tieuDe { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public string productCode { get; set; }
        public string moTa { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Pricesales { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string SeoMoTa { get; set; }
        public string SeoTuKhoa { get; set; }
        public string SeoTieuDe { get; set; }
        public string isHome { get; set; }
        public string isFeature { get; set; }
        public string isHost { get; set; }
        public string isSale { get; set; }
        public string biDanh { get; set; }
    
        public virtual tb_LoaiSanPham tb_LoaiSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_orderDeTail> tb_orderDeTail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ProductImage> tb_ProductImage { get; set; }
    }
}
