//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanDT.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ThongBaoMoi
    {
        public int ID { get; set; }
        public string tieuDe { get; set; }
        public Nullable<int> Categoryld { get; set; }
        public string moTa { get; set; }
        public string image { get; set; }
        public string SeoTieuDe { get; set; }
        public string SeoMoTa { get; set; }
        public string SeoTuKhoa { get; set; }
        public string biDanh { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> idNhanVien { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual tb_Category tb_Category { get; set; }
    }
}
