//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanDT.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WEBSITE_BANHANGEntities1 : DbContext
    {
        public WEBSITE_BANHANGEntities1()
            : base("name=WEBSITE_BANHANGEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACOUNT> ACOUNTs { get; set; }
        public virtual DbSet<CHUCNANG> CHUCNANGs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NhanVien_ChucNang> NhanVien_ChucNang { get; set; }
        public virtual DbSet<PHANQUYEN> PHANQUYENs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tb_LoaiSanPham> tb_LoaiSanPham { get; set; }
        public virtual DbSet<tb_Order> tb_Order { get; set; }
        public virtual DbSet<tb_orderDeTail> tb_orderDeTail { get; set; }
        public virtual DbSet<tb_postBaiViet> tb_postBaiViet { get; set; }
        public virtual DbSet<TB_PRODUCT> TB_PRODUCT { get; set; }
        public virtual DbSet<tb_Category> tb_Category { get; set; }
        public virtual DbSet<tb_ThongBaoMoi> tb_ThongBaoMoi { get; set; }
        public virtual DbSet<TB_datNhanThongBao> TB_datNhanThongBao { get; set; }
        public virtual DbSet<tb_ProductImage> tb_ProductImage { get; set; }
    }
}
